/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgentProfile {
  'status' : ApprovalStatus,
  'faceEmbeddings' : FaceEmbeddings,
  'principal' : Principal,
  'name' : string,
  'email' : string,
  'mobile' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CallLog {
  'id' : string,
  'duration' : bigint,
  'callType' : string,
  'participant' : ChatParticipant,
  'timestamp' : Time,
}
export type ChatParticipant = { 'agent' : string } |
  { 'customer' : string } |
  { 'lead' : string };
export interface Customer {
  'assignedAgent' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : [] | [string],
  'requirement' : Requirement,
  'mobile' : string,
  'followUpStatus' : string,
}
export type FaceEmbeddings = Uint8Array;
export interface FollowUp {
  'id' : string,
  'followUpTime' : Time,
  'status' : string,
  'linkedId' : string,
  'agent' : string,
  'createdAt' : Time,
  'type' : string,
  'remarks' : string,
}
export interface Lead {
  'status' : LeadStatus,
  'assignedAgent' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'email' : [] | [string],
  'requirement' : LeadRequirement,
  'remarksTimestamp' : [] | [Time],
  'mobile' : string,
  'remarks' : [] | [string],
}
export type LeadRequirement = { 'Fully_furnished_flat' : null } |
  { 'RWA_flat' : null } |
  { 'Semi_furnished_flat' : null };
export type LeadStatus = { 'new' : null } |
  { 'lost' : null } |
  { 'going_on' : null } |
  { 'converted' : null };
export type MessageDirection = { 'sent' : null } |
  { 'received' : null };
export type MessageStatus = { 'pending' : null } |
  { 'read' : null } |
  { 'delivered' : null };
export type Requirement = { 'Interior' : null } |
  { 'Fully_furnished_flat' : null } |
  { 'Rent' : null } |
  { 'Sell' : null } |
  { 'RWA_flat' : null } |
  { 'Purchase' : null } |
  { 'Semi_furnished_flat' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhatsAppMessage {
  'id' : string,
  'status' : MessageStatus,
  'direction' : MessageDirection,
  'content' : string,
  'participant' : ChatParticipant,
  'messageType' : string,
  'timestamp' : Time,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCallLog' : ActorMethod<[ChatParticipant, bigint, string], string>,
  'addCustomer' : ActorMethod<
    [string, string, [] | [string], Requirement, string, string],
    string
  >,
  'addFollowUp' : ActorMethod<
    [string, string, string, Time, string, string],
    string
  >,
  'addLead' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      LeadStatus,
      LeadRequirement,
      string,
      string,
      [] | [string],
      [] | [bigint],
    ],
    string
  >,
  'addWhatsAppMessage' : ActorMethod<
    [ChatParticipant, string, MessageDirection, string, MessageStatus],
    string
  >,
  'approveAgent' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAgent' : ActorMethod<[string], undefined>,
  'deleteFollowUp' : ActorMethod<[string], undefined>,
  'getAgentLoginTimesAndStatus' : ActorMethod<
    [],
    Array<[string, Time, boolean]>
  >,
  'getAgentProfileByCaller' : ActorMethod<[], AgentProfile>,
  'getAllAgentProfiles' : ActorMethod<[], Array<AgentProfile>>,
  'getCallLogs' : ActorMethod<[], Array<[string, CallLog]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomers' : ActorMethod<[], Array<[string, Customer]>>,
  'getFollowUps' : ActorMethod<[], Array<[string, FollowUp]>>,
  'getLeads' : ActorMethod<[], Array<[string, Lead]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWhatsAppMessages' : ActorMethod<[], Array<[string, WhatsAppMessage]>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'loginAgent' : ActorMethod<[Uint8Array], undefined>,
  'logoutAgent' : ActorMethod<[], undefined>,
  'makeHttpGetRequest' : ActorMethod<[string], string>,
  'registerAgent' : ActorMethod<
    [string, string, string, Uint8Array],
    undefined
  >,
  'rejectAgent' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAgentProfile' : ActorMethod<[string, string, string], undefined>,
  'updateFollowUp' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];