/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatParticipant = IDL.Variant({
  'agent' : IDL.Text,
  'customer' : IDL.Text,
  'lead' : IDL.Text,
});
export const Requirement = IDL.Variant({
  'Interior' : IDL.Null,
  'Fully_furnished_flat' : IDL.Null,
  'Rent' : IDL.Null,
  'Sell' : IDL.Null,
  'RWA_flat' : IDL.Null,
  'Purchase' : IDL.Null,
  'Semi_furnished_flat' : IDL.Null,
});
export const Time = IDL.Int;
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'lost' : IDL.Null,
  'going_on' : IDL.Null,
  'converted' : IDL.Null,
});
export const LeadRequirement = IDL.Variant({
  'Fully_furnished_flat' : IDL.Null,
  'RWA_flat' : IDL.Null,
  'Semi_furnished_flat' : IDL.Null,
});
export const MessageDirection = IDL.Variant({
  'sent' : IDL.Null,
  'received' : IDL.Null,
});
export const MessageStatus = IDL.Variant({
  'pending' : IDL.Null,
  'read' : IDL.Null,
  'delivered' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const FaceEmbeddings = IDL.Vec(IDL.Nat8);
export const AgentProfile = IDL.Record({
  'status' : ApprovalStatus,
  'faceEmbeddings' : FaceEmbeddings,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'mobile' : IDL.Text,
});
export const CallLog = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Nat,
  'callType' : IDL.Text,
  'participant' : ChatParticipant,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Customer = IDL.Record({
  'assignedAgent' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Nat64,
  'email' : IDL.Opt(IDL.Text),
  'requirement' : Requirement,
  'mobile' : IDL.Text,
  'followUpStatus' : IDL.Text,
});
export const FollowUp = IDL.Record({
  'id' : IDL.Text,
  'followUpTime' : Time,
  'status' : IDL.Text,
  'linkedId' : IDL.Text,
  'agent' : IDL.Text,
  'createdAt' : Time,
  'type' : IDL.Text,
  'remarks' : IDL.Text,
});
export const Lead = IDL.Record({
  'status' : LeadStatus,
  'assignedAgent' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'requirement' : LeadRequirement,
  'remarksTimestamp' : IDL.Opt(Time),
  'mobile' : IDL.Text,
  'remarks' : IDL.Opt(IDL.Text),
});
export const WhatsAppMessage = IDL.Record({
  'id' : IDL.Text,
  'status' : MessageStatus,
  'direction' : MessageDirection,
  'content' : IDL.Text,
  'participant' : ChatParticipant,
  'messageType' : IDL.Text,
  'timestamp' : Time,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCallLog' : IDL.Func([ChatParticipant, IDL.Nat, IDL.Text], [IDL.Text], []),
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), Requirement, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addFollowUp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        LeadStatus,
        LeadRequirement,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat64),
      ],
      [IDL.Text],
      [],
    ),
  'addWhatsAppMessage' : IDL.Func(
      [ChatParticipant, IDL.Text, MessageDirection, IDL.Text, MessageStatus],
      [IDL.Text],
      [],
    ),
  'approveAgent' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAgent' : IDL.Func([IDL.Text], [], []),
  'deleteFollowUp' : IDL.Func([IDL.Text], [], []),
  'getAgentLoginTimesAndStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Time, IDL.Bool))],
      ['query'],
    ),
  'getAgentProfileByCaller' : IDL.Func([], [AgentProfile], ['query']),
  'getAllAgentProfiles' : IDL.Func([], [IDL.Vec(AgentProfile)], ['query']),
  'getCallLogs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, CallLog))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Customer))],
      ['query'],
    ),
  'getFollowUps' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, FollowUp))],
      ['query'],
    ),
  'getLeads' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, Lead))], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWhatsAppMessages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, WhatsAppMessage))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'loginAgent' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'logoutAgent' : IDL.Func([], [], []),
  'makeHttpGetRequest' : IDL.Func([IDL.Text], [IDL.Text], []),
  'registerAgent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
  'rejectAgent' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAgentProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateFollowUp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatParticipant = IDL.Variant({
    'agent' : IDL.Text,
    'customer' : IDL.Text,
    'lead' : IDL.Text,
  });
  const Requirement = IDL.Variant({
    'Interior' : IDL.Null,
    'Fully_furnished_flat' : IDL.Null,
    'Rent' : IDL.Null,
    'Sell' : IDL.Null,
    'RWA_flat' : IDL.Null,
    'Purchase' : IDL.Null,
    'Semi_furnished_flat' : IDL.Null,
  });
  const Time = IDL.Int;
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'lost' : IDL.Null,
    'going_on' : IDL.Null,
    'converted' : IDL.Null,
  });
  const LeadRequirement = IDL.Variant({
    'Fully_furnished_flat' : IDL.Null,
    'RWA_flat' : IDL.Null,
    'Semi_furnished_flat' : IDL.Null,
  });
  const MessageDirection = IDL.Variant({
    'sent' : IDL.Null,
    'received' : IDL.Null,
  });
  const MessageStatus = IDL.Variant({
    'pending' : IDL.Null,
    'read' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const FaceEmbeddings = IDL.Vec(IDL.Nat8);
  const AgentProfile = IDL.Record({
    'status' : ApprovalStatus,
    'faceEmbeddings' : FaceEmbeddings,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const CallLog = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Nat,
    'callType' : IDL.Text,
    'participant' : ChatParticipant,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Customer = IDL.Record({
    'assignedAgent' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat64,
    'email' : IDL.Opt(IDL.Text),
    'requirement' : Requirement,
    'mobile' : IDL.Text,
    'followUpStatus' : IDL.Text,
  });
  const FollowUp = IDL.Record({
    'id' : IDL.Text,
    'followUpTime' : Time,
    'status' : IDL.Text,
    'linkedId' : IDL.Text,
    'agent' : IDL.Text,
    'createdAt' : Time,
    'type' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const Lead = IDL.Record({
    'status' : LeadStatus,
    'assignedAgent' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'requirement' : LeadRequirement,
    'remarksTimestamp' : IDL.Opt(Time),
    'mobile' : IDL.Text,
    'remarks' : IDL.Opt(IDL.Text),
  });
  const WhatsAppMessage = IDL.Record({
    'id' : IDL.Text,
    'status' : MessageStatus,
    'direction' : MessageDirection,
    'content' : IDL.Text,
    'participant' : ChatParticipant,
    'messageType' : IDL.Text,
    'timestamp' : Time,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCallLog' : IDL.Func(
        [ChatParticipant, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addCustomer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          Requirement,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'addFollowUp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          LeadStatus,
          LeadRequirement,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat64),
        ],
        [IDL.Text],
        [],
      ),
    'addWhatsAppMessage' : IDL.Func(
        [ChatParticipant, IDL.Text, MessageDirection, IDL.Text, MessageStatus],
        [IDL.Text],
        [],
      ),
    'approveAgent' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAgent' : IDL.Func([IDL.Text], [], []),
    'deleteFollowUp' : IDL.Func([IDL.Text], [], []),
    'getAgentLoginTimesAndStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Time, IDL.Bool))],
        ['query'],
      ),
    'getAgentProfileByCaller' : IDL.Func([], [AgentProfile], ['query']),
    'getAllAgentProfiles' : IDL.Func([], [IDL.Vec(AgentProfile)], ['query']),
    'getCallLogs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, CallLog))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Customer))],
        ['query'],
      ),
    'getFollowUps' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, FollowUp))],
        ['query'],
      ),
    'getLeads' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, Lead))], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWhatsAppMessages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, WhatsAppMessage))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'loginAgent' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'logoutAgent' : IDL.Func([], [], []),
    'makeHttpGetRequest' : IDL.Func([IDL.Text], [IDL.Text], []),
    'registerAgent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
    'rejectAgent' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAgentProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateFollowUp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };