/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface CallLog {
    id: string;
    duration: bigint;
    callType: string;
    participant: ChatParticipant;
    timestamp: Time;
}
export interface WhatsAppMessage {
    id: string;
    status: MessageStatus;
    direction: MessageDirection;
    content: string;
    participant: ChatParticipant;
    messageType: string;
    timestamp: Time;
}
export interface Customer {
    assignedAgent: string;
    name: string;
    createdAt: bigint;
    email?: string;
    requirement: Requirement;
    mobile: string;
    followUpStatus: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Lead {
    status: LeadStatus;
    assignedAgent: string;
    name: string;
    createdAt: Time;
    description: string;
    email?: string;
    requirement: LeadRequirement;
    remarksTimestamp?: Time;
    mobile: string;
    remarks?: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type ChatParticipant = {
    __kind__: "agent";
    agent: string;
} | {
    __kind__: "customer";
    customer: string;
} | {
    __kind__: "lead";
    lead: string;
};
export type FaceEmbeddings = Uint8Array;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface FollowUp {
    id: string;
    followUpTime: Time;
    status: string;
    linkedId: string;
    agent: string;
    createdAt: Time;
    type: string;
    remarks: string;
}
export interface UserProfile {
    name: string;
    email: string;
    mobile: string;
}
export interface AgentProfile {
    status: ApprovalStatus;
    faceEmbeddings: FaceEmbeddings;
    principal: Principal;
    name: string;
    email: string;
    mobile: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum LeadRequirement {
    Fully_furnished_flat = "Fully_furnished_flat",
    RWA_flat = "RWA_flat",
    Semi_furnished_flat = "Semi_furnished_flat"
}
export enum LeadStatus {
    new_ = "new",
    lost = "lost",
    going_on = "going_on",
    converted = "converted"
}
export enum MessageDirection {
    sent = "sent",
    received = "received"
}
export enum MessageStatus {
    pending = "pending",
    read = "read",
    delivered = "delivered"
}
export enum Requirement {
    Interior = "Interior",
    Fully_furnished_flat = "Fully_furnished_flat",
    Rent = "Rent",
    Sell = "Sell",
    RWA_flat = "RWA_flat",
    Purchase = "Purchase",
    Semi_furnished_flat = "Semi_furnished_flat"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCallLog(participant: ChatParticipant, duration: bigint, callType: string): Promise<string>;
    addCustomer(name: string, mobile: string, email: string | null, requirement: Requirement, assignedAgent: string, followUpStatus: string): Promise<string>;
    addFollowUp(linkedId: string, type: string, agent: string, followUpTime: Time, remarks: string, status: string): Promise<string>;
    addLead(name: string, mobile: string, email: string | null, status: LeadStatus, requirement: LeadRequirement, assignedAgent: string, description: string, remarks: string | null, remarksTimestamp: bigint | null): Promise<string>;
    addWhatsAppMessage(participant: ChatParticipant, content: string, direction: MessageDirection, messageType: string, status: MessageStatus): Promise<string>;
    approveAgent(mobile: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAgent(mobile: string): Promise<void>;
    deleteFollowUp(followUpId: string): Promise<void>;
    getAgentLoginTimesAndStatus(): Promise<Array<[string, Time, boolean]>>;
    getAgentProfileByCaller(): Promise<AgentProfile>;
    getAllAgentProfiles(): Promise<Array<AgentProfile>>;
    getCallLogs(): Promise<Array<[string, CallLog]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomers(): Promise<Array<[string, Customer]>>;
    getFollowUps(): Promise<Array<[string, FollowUp]>>;
    getLeads(): Promise<Array<[string, Lead]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWhatsAppMessages(): Promise<Array<[string, WhatsAppMessage]>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    loginAgent(faceEmbeddings: Uint8Array): Promise<void>;
    logoutAgent(): Promise<void>;
    makeHttpGetRequest(url: string): Promise<string>;
    registerAgent(name: string, mobile: string, email: string, faceEmbeddings: Uint8Array): Promise<void>;
    rejectAgent(mobile: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAgentProfile(mobile: string, name: string, email: string): Promise<void>;
    updateFollowUp(followUpId: string, remarks: string, status: string): Promise<void>;
}
import type { AgentProfile as _AgentProfile, ApprovalStatus as _ApprovalStatus, CallLog as _CallLog, ChatParticipant as _ChatParticipant, Customer as _Customer, FaceEmbeddings as _FaceEmbeddings, Lead as _Lead, LeadRequirement as _LeadRequirement, LeadStatus as _LeadStatus, MessageDirection as _MessageDirection, MessageStatus as _MessageStatus, Requirement as _Requirement, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, WhatsAppMessage as _WhatsAppMessage } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCallLog(arg0: ChatParticipant, arg1: bigint, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCallLog(to_candid_ChatParticipant_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCallLog(to_candid_ChatParticipant_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async addCustomer(arg0: string, arg1: string, arg2: string | null, arg3: Requirement, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_Requirement_n4(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_Requirement_n4(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async addFollowUp(arg0: string, arg1: string, arg2: string, arg3: Time, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addFollowUp(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFollowUp(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addLead(arg0: string, arg1: string, arg2: string | null, arg3: LeadStatus, arg4: LeadRequirement, arg5: string, arg6: string, arg7: string | null, arg8: bigint | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addLead(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_LeadStatus_n6(this._uploadFile, this._downloadFile, arg3), to_candid_LeadRequirement_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLead(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_LeadStatus_n6(this._uploadFile, this._downloadFile, arg3), to_candid_LeadRequirement_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async addWhatsAppMessage(arg0: ChatParticipant, arg1: string, arg2: MessageDirection, arg3: string, arg4: MessageStatus): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addWhatsAppMessage(to_candid_ChatParticipant_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_MessageDirection_n11(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_MessageStatus_n13(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWhatsAppMessage(to_candid_ChatParticipant_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_MessageDirection_n11(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_MessageStatus_n13(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async approveAgent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAgent(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAgent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAgent(arg0);
            return result;
        }
    }
    async deleteFollowUp(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFollowUp(arg0);
            return result;
        }
    }
    async getAgentLoginTimesAndStatus(): Promise<Array<[string, Time, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentLoginTimesAndStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentLoginTimesAndStatus();
            return result;
        }
    }
    async getAgentProfileByCaller(): Promise<AgentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentProfileByCaller();
                return from_candid_AgentProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentProfileByCaller();
            return from_candid_AgentProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAgentProfiles(): Promise<Array<AgentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgentProfiles();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgentProfiles();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallLogs(): Promise<Array<[string, CallLog]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallLogs();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallLogs();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<[string, Customer]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowUps(): Promise<Array<[string, FollowUp]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUps();
            return result;
        }
    }
    async getLeads(): Promise<Array<[string, Lead]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeads();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeads();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWhatsAppMessages(): Promise<Array<[string, WhatsAppMessage]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhatsAppMessages();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhatsAppMessages();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginAgent(arg0: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.loginAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginAgent(arg0);
            return result;
        }
    }
    async logoutAgent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutAgent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutAgent();
            return result;
        }
    }
    async makeHttpGetRequest(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.makeHttpGetRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeHttpGetRequest(arg0);
            return result;
        }
    }
    async registerAgent(arg0: string, arg1: string, arg2: string, arg3: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAgent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAgent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async rejectAgent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectAgent(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAgentProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgentProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgentProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async updateFollowUp(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFollowUp(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFollowUp(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AgentProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentProfile): AgentProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_CallLog_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallLog): CallLog {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ChatParticipant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatParticipant): ChatParticipant {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_LeadRequirement_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadRequirement): LeadRequirement {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_MessageDirection_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageDirection): MessageDirection {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_MessageStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageStatus): MessageStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Requirement_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Requirement): Requirement {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_WhatsAppMessage_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WhatsAppMessage): WhatsAppMessage {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    faceEmbeddings: _FaceEmbeddings;
    principal: Principal;
    name: string;
    email: string;
    mobile: string;
}): {
    status: ApprovalStatus;
    faceEmbeddings: FaceEmbeddings;
    principal: Principal;
    name: string;
    email: string;
    mobile: string;
} {
    return {
        status: from_candid_ApprovalStatus_n19(_uploadFile, _downloadFile, value.status),
        faceEmbeddings: value.faceEmbeddings,
        principal: value.principal,
        name: value.name,
        email: value.email,
        mobile: value.mobile
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: bigint;
    callType: string;
    participant: _ChatParticipant;
    timestamp: _Time;
}): {
    id: string;
    duration: bigint;
    callType: string;
    participant: ChatParticipant;
    timestamp: Time;
} {
    return {
        id: value.id,
        duration: value.duration,
        callType: value.callType,
        participant: from_candid_ChatParticipant_n26(_uploadFile, _downloadFile, value.participant),
        timestamp: value.timestamp
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedAgent: string;
    name: string;
    createdAt: bigint;
    email: [] | [string];
    requirement: _Requirement;
    mobile: string;
    followUpStatus: string;
}): {
    assignedAgent: string;
    name: string;
    createdAt: bigint;
    email?: string;
    requirement: Requirement;
    mobile: string;
    followUpStatus: string;
} {
    return {
        assignedAgent: value.assignedAgent,
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.email)),
        requirement: from_candid_Requirement_n36(_uploadFile, _downloadFile, value.requirement),
        mobile: value.mobile,
        followUpStatus: value.followUpStatus
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LeadStatus;
    assignedAgent: string;
    name: string;
    createdAt: _Time;
    description: string;
    email: [] | [string];
    requirement: _LeadRequirement;
    remarksTimestamp: [] | [_Time];
    mobile: string;
    remarks: [] | [string];
}): {
    status: LeadStatus;
    assignedAgent: string;
    name: string;
    createdAt: Time;
    description: string;
    email?: string;
    requirement: LeadRequirement;
    remarksTimestamp?: Time;
    mobile: string;
    remarks?: string;
} {
    return {
        status: from_candid_LeadStatus_n42(_uploadFile, _downloadFile, value.status),
        assignedAgent: value.assignedAgent,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        email: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.email)),
        requirement: from_candid_LeadRequirement_n44(_uploadFile, _downloadFile, value.requirement),
        remarksTimestamp: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.remarksTimestamp)),
        mobile: value.mobile,
        remarks: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.remarks))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _MessageStatus;
    direction: _MessageDirection;
    content: string;
    participant: _ChatParticipant;
    messageType: string;
    timestamp: _Time;
}): {
    id: string;
    status: MessageStatus;
    direction: MessageDirection;
    content: string;
    participant: ChatParticipant;
    messageType: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        status: from_candid_MessageStatus_n51(_uploadFile, _downloadFile, value.status),
        direction: from_candid_MessageDirection_n53(_uploadFile, _downloadFile, value.direction),
        content: value.content,
        participant: from_candid_ChatParticipant_n26(_uploadFile, _downloadFile, value.participant),
        messageType: value.messageType,
        timestamp: value.timestamp
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n19(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _CallLog]): [string, CallLog] {
    return [
        value[0],
        from_candid_CallLog_n24(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Customer]): [string, Customer] {
    return [
        value[0],
        from_candid_Customer_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Lead]): [string, Lead] {
    return [
        value[0],
        from_candid_Lead_n40(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _WhatsAppMessage]): [string, WhatsAppMessage] {
    return [
        value[0],
        from_candid_WhatsAppMessage_n49(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    agent: string;
} | {
    customer: string;
} | {
    lead: string;
}): {
    __kind__: "agent";
    agent: string;
} | {
    __kind__: "customer";
    customer: string;
} | {
    __kind__: "lead";
    lead: string;
} {
    return "agent" in value ? {
        __kind__: "agent",
        agent: value.agent
    } : "customer" in value ? {
        __kind__: "customer",
        customer: value.customer
    } : "lead" in value ? {
        __kind__: "lead",
        lead: value.lead
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Interior: null;
} | {
    Fully_furnished_flat: null;
} | {
    Rent: null;
} | {
    Sell: null;
} | {
    RWA_flat: null;
} | {
    Purchase: null;
} | {
    Semi_furnished_flat: null;
}): Requirement {
    return "Interior" in value ? Requirement.Interior : "Fully_furnished_flat" in value ? Requirement.Fully_furnished_flat : "Rent" in value ? Requirement.Rent : "Sell" in value ? Requirement.Sell : "RWA_flat" in value ? Requirement.RWA_flat : "Purchase" in value ? Requirement.Purchase : "Semi_furnished_flat" in value ? Requirement.Semi_furnished_flat : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    lost: null;
} | {
    going_on: null;
} | {
    converted: null;
}): LeadStatus {
    return "new" in value ? LeadStatus.new : "lost" in value ? LeadStatus.lost : "going_on" in value ? LeadStatus.going_on : "converted" in value ? LeadStatus.converted : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Fully_furnished_flat: null;
} | {
    RWA_flat: null;
} | {
    Semi_furnished_flat: null;
}): LeadRequirement {
    return "Fully_furnished_flat" in value ? LeadRequirement.Fully_furnished_flat : "RWA_flat" in value ? LeadRequirement.RWA_flat : "Semi_furnished_flat" in value ? LeadRequirement.Semi_furnished_flat : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    read: null;
} | {
    delivered: null;
}): MessageStatus {
    return "pending" in value ? MessageStatus.pending : "read" in value ? MessageStatus.read : "delivered" in value ? MessageStatus.delivered : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    received: null;
}): MessageDirection {
    return "sent" in value ? MessageDirection.sent : "received" in value ? MessageDirection.received : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AgentProfile>): Array<AgentProfile> {
    return value.map((x)=>from_candid_AgentProfile_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _CallLog]>): Array<[string, CallLog]> {
    return value.map((x)=>from_candid_tuple_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Customer]>): Array<[string, Customer]> {
    return value.map((x)=>from_candid_tuple_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Lead]>): Array<[string, Lead]> {
    return value.map((x)=>from_candid_tuple_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _WhatsAppMessage]>): Array<[string, WhatsAppMessage]> {
    return value.map((x)=>from_candid_tuple_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n56(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_ChatParticipant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatParticipant): _ChatParticipant {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_LeadRequirement_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadRequirement): _LeadRequirement {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_MessageDirection_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageDirection): _MessageDirection {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_MessageStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageStatus): _MessageStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Requirement_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Requirement): _Requirement {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageDirection): {
    sent: null;
} | {
    received: null;
} {
    return value == MessageDirection.sent ? {
        sent: null
    } : value == MessageDirection.received ? {
        received: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageStatus): {
    pending: null;
} | {
    read: null;
} | {
    delivered: null;
} {
    return value == MessageStatus.pending ? {
        pending: null
    } : value == MessageStatus.read ? {
        read: null
    } : value == MessageStatus.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "agent";
    agent: string;
} | {
    __kind__: "customer";
    customer: string;
} | {
    __kind__: "lead";
    lead: string;
}): {
    agent: string;
} | {
    customer: string;
} | {
    lead: string;
} {
    return value.__kind__ === "agent" ? {
        agent: value.agent
    } : value.__kind__ === "customer" ? {
        customer: value.customer
    } : value.__kind__ === "lead" ? {
        lead: value.lead
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Requirement): {
    Interior: null;
} | {
    Fully_furnished_flat: null;
} | {
    Rent: null;
} | {
    Sell: null;
} | {
    RWA_flat: null;
} | {
    Purchase: null;
} | {
    Semi_furnished_flat: null;
} {
    return value == Requirement.Interior ? {
        Interior: null
    } : value == Requirement.Fully_furnished_flat ? {
        Fully_furnished_flat: null
    } : value == Requirement.Rent ? {
        Rent: null
    } : value == Requirement.Sell ? {
        Sell: null
    } : value == Requirement.RWA_flat ? {
        RWA_flat: null
    } : value == Requirement.Purchase ? {
        Purchase: null
    } : value == Requirement.Semi_furnished_flat ? {
        Semi_furnished_flat: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    new: null;
} | {
    lost: null;
} | {
    going_on: null;
} | {
    converted: null;
} {
    return value == LeadStatus.new ? {
        new_: null
    } : value == LeadStatus.lost ? {
        lost: null
    } : value == LeadStatus.going_on ? {
        going_on: null
    } : value == LeadStatus.converted ? {
        converted: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadRequirement): {
    Fully_furnished_flat: null;
} | {
    RWA_flat: null;
} | {
    Semi_furnished_flat: null;
} {
    return value == LeadRequirement.Fully_furnished_flat ? {
        Fully_furnished_flat: null
    } : value == LeadRequirement.RWA_flat ? {
        RWA_flat: null
    } : value == LeadRequirement.Semi_furnished_flat ? {
        Semi_furnished_flat: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
